name = "internetcheck"
main ="./_worker.js"

account_id = "b53a94dbb915dc3f10629470c2cf2fed"

compatibility_date = "2025-05-01"

routes = [
  "http://internetcheck.xyz/*",
  "http://*.internetcheck.xyz/*",
  "http://networktest.xyz/*",
  "http://*.networktest.xyz/*",
  "http://networkcheck.xyz/*",
  "http://*.networkcheck.xyz/*",
  "http://http.rocks/*",
  "http://*.http.rocks/*"
]

workers_dev = false

[site]
bucket = "."
